[package]
name = "rustwarp"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.25.0"
wgpu = "0.14"
env_logger = "0.9.1"
pollster = "0.2.5"
futures-intrusive = "0.4"
bytemuck = { version = "1.12.1", features = ["derive"] }
